#!/bin/zsh
#
# .zstyles - Set zstyle settings for plugins that need them.
#

#
# Antidote
#

# zstyle ':antidote:bundle' file ${ZDOTDIR:-~}/.zplugins.txt
# zstyle ':antidote:bundle' use-friendly-names 'yes'

# oh-my-zsh update reminder
# actual update managed by chezmoi
zstyle ':omz:update' mode reminder
